<!DOCTYPE html>
<html lang="en">
	<head>
		<title>cs410green Bios</title>
		<?php require 'head.php'; ?>
	</head>
	<body>
		<?php require 'navbar.php'; ?>

		<div class="container-fluid">

			<div class="starter-template">
				<h2 id="thumbnails-bios">Green Team = Best Team</h2>
				<div data-id="member-bios">
					<div class="row-fluid">
						<!-- <div class="row-same-height"> -->
						<div class="col-sm-6 col-md-4">
							<div class="thumbnail">
								<img src="" data-holder-rendered="true" style="height: 200px; width: 200px; display: block;">
								<div class="caption">
									<h3>Thumbnail Caption</h3>
									<p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
									<!--
									<p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
									-->									
								</div>
							</div>
						</div>
						<div class="col-sm-6 col-md-4">
							<div class="thumbnail">
								<img src="" data-holder-rendered="true" style="height: 200px; width: 200px; display: block;">
								<div class="caption">
									<h3>Thumbnail Caption</h3>
									<p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
									<!--
									<p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
									-->									
								</div>
							</div>
						</div>
						<div class="clearfix visible-sm-block"></div>
						<div class="col-sm-6 col-md-4">
							<div class="thumbnail">
								<img src="images/eWichern.png" data-holder-rendered="true" style="height: 200px; width: 200px; display: block;">
								<div class="caption">
									<h3>Erik Wichern</h3>
									<p>Erik Wichern is an undergraduate student at Old Dominion University pursuing a B.S. in Computer Science. He currently works in the human services field, but has academic and professional experience in IT and software development, including an internship with the e-Business Services Division at Redhat Linux many years ago. Erik lives in Winchester, VA, geeks out over mobile devices and technology, and is interested in applications and algorithm development.</p>
									<!--
									<p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
									-->									
								</div>
							</div>
						</div>
						<div class="col-sm-6 col-md-4">
							<div class="thumbnail">
								<img src="" data-holder-rendered="true" style="height: 200px; width: 200px; display: block;">
								<div class="caption">
									<h3>Thumbnail Caption</h3>
									<p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
									<!--
									<p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
									-->									
								</div>
							</div>
						</div>
						<div class="clearfix visible-sm-block"></div>
						<div class="col-sm-6 col-md-4">
							<div class="thumbnail">
								<img src="images/dWiggins.jpg" data-holder-rendered="true" style="height: 200px; width: 200px; display: block;">
								<div class="caption">
									<h3>Diamon Wiggins</h3>
									<p>Diamon Wiggins is a 23 year old undergraduate computer science student at Old Dominion University. He was born and raised in Norfolk, Virginia, and has always enjoyed working with computers. Diamon is currently employed as a systems administrator by the computer science department at ODU. His primary focus is Windows Administration.</p>
									<!--
									<p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
									-->
								</div>
							</div>
						</div>
						<div class="col-sm-6 col-md-4">
							<div class="thumbnail">
								<img src="" data-holder-rendered="true" style="height: 200px; width: 200px; display: block;">
								<div class="caption">
									<h3>Thumbnail Caption</h3>
									<p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
									<!--
									<p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
									-->									
								</div>
							</div>
						</div>
						<!-- </div> /row-same-height -->
					</div><!-- /row -->

				</div><!-- /member-bios-->
			</div>
		</div><!-- /.container -->

		<?php require 'scripts.php'; ?>
	</body>
</html>
