<!DOCTYPE html>
<html lang="en">
	<head>
		<title>cs410green References</title>
		<?php require 'head.php'; ?>
	</head>
	<body>
		<?php require 'navbar.php'; ?>

		<div class="container">

			<div class="starter-template">
				<h1>References</h1>
				<p class="lead">
				Environmental Protection Agency - Climate Change: Basic Information</br>
				<a href="http://www.epa.gov/climatechange/basics/">http://www.epa.gov/climatechange/basics</a></br></br>
				2014 National Climate Assessment</br>
				<a href="http://nca2014.globalchange.gov/report">http://nca2014.globalchange.gov/report</a></br></br>
				Natural Resources Defense Council - Climate Change Health Threats in Virginia</br>
				<a href="http://www.nrdc.org/health/climate/va.asp">http://www.nrdc.org/health/climate/va.asp</a></br></br>				
				</p>
			</div>

		</div><!-- /.container -->

		<?php require 'scripts.php'; ?>
	</body>
</html>
